import DefaultLayout from "@/components/DefaultLayout";
import Head from "next/head";

export default function Home() {
  return (
    <DefaultLayout>
      <Head>
        <title>FirstCall Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className="section">Hello World!</section>
    </DefaultLayout>
  );
}
